node-check:
  # Use the official docker image.
  image: node:latest
  stage: build
  script:
    - apt install imagemagick
    - npm install -g grunt
    - npm install
    - |
      cp res/deployment/default/config.yml config.yml
      cp -r res/deployment/default/source source/
      cp -r res/deployment/default/custom custom/
    - timeout 2m npm start

docker-build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker info
  script:
    - docker build --pull .

docker-publish:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  before_script:
    - docker info
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      else
        tag=":$CI_COMMIT_REF_SLUG"
        echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
      fi
    - docker build --pull -t "$CI_REGISTRY/$CI_PROJECT_PATH${tag}" .
    - docker push "$CI_REGISTRY/$CI_PROJECT_PATH${tag}"
